spring:
  datasource:
    username: root
    password: Pass@123
    url: jdbc:mysql://localhost:3306/zee5appProd
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.zee.zee5app.utils.CustomTableNameStrategy
    show-sql: true